# Generated by Django 4.1.2 on 2022-10-21 19:40

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('avatar', models.ImageField(upload_to='uploads/%Y/%m')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Chuong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stt_chuong', models.IntegerField()),
                ('ch_ten', models.CharField(max_length=255)),
                ('noi_dung', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TheLoai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tl_ten', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Truyen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tr_ten', models.CharField(max_length=255)),
                ('ngay_phat_hanh', models.DateTimeField(auto_now_add=True)),
                ('tac_gia', models.CharField(max_length=255)),
                ('anh', models.ImageField(upload_to='uploads/%Y/%m')),
                ('tong_so_tap', models.IntegerField()),
                ('so_tap_da_phat_hanh', models.IntegerField()),
                ('lich_phat_hanh', models.TextField(blank=True, null=True)),
                ('so_luot_thich', models.IntegerField()),
                ('diem_danh_gia', models.DecimalField(decimal_places=2, max_digits=5)),
                ('so_luong_doc', models.IntegerField()),
                ('mo_ta', models.TextField(blank=True, null=True)),
                ('tl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.theloai')),
                ('us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='YeuThich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian', models.DateTimeField(auto_now_add=True)),
                ('tr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.truyen')),
                ('us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LichSu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian', models.DateTimeField(auto_now_add=True)),
                ('ch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.chuong')),
                ('tr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.truyen')),
                ('us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chuong',
            name='tr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.truyen'),
        ),
        migrations.AddField(
            model_name='chuong',
            name='us',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BinhLuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noi_dung', models.TextField(blank=True, null=True)),
                ('thoi_gian', models.DateTimeField(auto_now_add=True)),
                ('ch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.chuong')),
                ('tr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.truyen')),
                ('us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
