# Generated by Django 4.1.2 on 2022-10-22 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_truyen_tl_truyen_tl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='LoveStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_name', models.CharField(max_length=255)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='uploads/%Y/%m')),
                ('total_chapters', models.IntegerField()),
                ('showtimes', models.TextField(blank=True, null=True)),
                ('likes', models.IntegerField()),
                ('rating', models.DecimalField(decimal_places=2, max_digits=5)),
                ('views', models.IntegerField()),
                ('introduce', models.TextField(blank=True, null=True)),
                ('category_name', models.ManyToManyField(blank=True, null=True, to='backend.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='chuong',
            name='tr',
        ),
        migrations.RemoveField(
            model_name='chuong',
            name='us',
        ),
        migrations.RemoveField(
            model_name='lichsu',
            name='ch',
        ),
        migrations.RemoveField(
            model_name='lichsu',
            name='tr',
        ),
        migrations.RemoveField(
            model_name='lichsu',
            name='us',
        ),
        migrations.RemoveField(
            model_name='truyen',
            name='tl',
        ),
        migrations.RemoveField(
            model_name='truyen',
            name='us',
        ),
        migrations.RemoveField(
            model_name='yeuthich',
            name='tr',
        ),
        migrations.RemoveField(
            model_name='yeuthich',
            name='us',
        ),
        migrations.DeleteModel(
            name='BinhLuan',
        ),
        migrations.DeleteModel(
            name='Chuong',
        ),
        migrations.DeleteModel(
            name='LichSu',
        ),
        migrations.DeleteModel(
            name='TheLoai',
        ),
        migrations.DeleteModel(
            name='Truyen',
        ),
        migrations.DeleteModel(
            name='YeuThich',
        ),
        migrations.AddField(
            model_name='lovestory',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.story'),
        ),
        migrations.AddField(
            model_name='lovestory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='history',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.story'),
        ),
        migrations.AddField(
            model_name='history',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.story'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chapter',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.story'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
