# Generated by Django 4.1.2 on 2022-10-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_savestory_comment_previous_comment_delete_lovestory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m'),
        ),
    ]
