# Generated by Django 4.1.2 on 2022-10-22 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_lovecomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='likes',
        ),
        migrations.AddField(
            model_name='lovecomment',
            name='like_dislike',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='story',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='story',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('like', models.IntegerField(default=0)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
