# Generated by Django 4.1.2 on 2022-10-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_remove_story_likes_lovecomment_like_dislike_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreview',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
