# Generated by Django 4.1.2 on 2022-10-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_bookreview_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to='uploads/%Y/%m'),
        ),
    ]
