# Generated by Django 4.1.2 on 2022-10-22 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='user',
        ),
    ]
